# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version = 0.4.0
maven_group = com.connorcode
archives_base_name = auto-reauth

# Dependencies
fabric_version=0.146.1+26.1.2
mod_menu_version=18.0.0-alpha.8
